[package]
name = "firefly-toml"
version = "0.1.1"
edition = "2024"
rust-version = "1.95.0"
authors = ["Firefly Zero team"]
description = "Rust macro for statically parsing firefly.toml"
repository = "https://github.com/firefly-zero/firefly-toml"
license = "MIT"
keywords = ["gamedev", "firefly-zero"]
categories = ["game-development", "no-std", "rendering", "api-bindings", "wasm"]

[lib]
proc-macro = true

[dependencies]
toml = "1.0.6"
serde = { version = "1.0.229", features = ["serde_derive"] }

[dev-dependencies]
snapshot-testing = "0.1.8"
firefly-rust = { version = "0.16.0", default-features = false }
